spring.application.name=spotify-api-service

# Server port
server.port=8083

# OAuth2 Configuration
spring.security.oauth2.client.registration.spotify.client-id=${e985eb67d938484ba10f72657287bed6}
spring.security.oauth2.client.registration.spotify.client-secret=${8cc7f04024cc4acead6f5376e321ac8d}
spring.security.oauth2.client.registration.spotify.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.spotify.redirect-uri=${http://localhost:8083}/api/spotify/callback
spring.security.oauth2.client.registration.spotify.scope=user-read-private,user-read-email,streaming,user-read-playback-state,user-modify-playback-state

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:spotifydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (Dev Only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console